server:
  forward-headers-strategy: framework

spring:
  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://${DEV_DB_HOST}:${DEV_DB_PORT}/dekk
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: ${DEV_REDIS_PORT}
      timeout: 500ms
      ssl:
        enabled: false
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
          max-wait: 1000ms

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: ${DEV_GOOGLE_REDIRECT_URI}
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${DEV_KAKAO_REDIRECT_URI}
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${DEV_GMAIL_USERNAME}
    password: ${DEV_GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  secret: ${DEV_JWT_SECRET_KEY}
  access-token-validity-in-seconds: 31536000
  refresh-token-validity-in-seconds: 31536000
  admin-access-token-validity-in-seconds: 31536000
  admin-refresh-token-validity-in-seconds: 31536000

app:
  oauth2:
    redirect-uri: "${DEV_FRONTEND_URL}/oauth2/redirect"
    login-page: "${DEV_FRONTEND_URL}/login"
    join-page: "${DEV_FRONTEND_URL}/join"
  cors:
    allowed-origins: ${DEV_ALLOWED_ORIGINS}
  cookie:
    domain: ${DEV_COOKIE_DOMAIN}
    secure: true

storage:
  region: ${DEV_AWS_S3_REGION}
  bucket: ${DEV_AWS_S3_RESOURCE_BUCKET}
  presigned-url-expiration: 5m
  cdn-base-url: ${DEV_CDN_BASE_URL}

loki:
  host: ${DEV_LOKI_HOST}

management:
  server:
    port: ${DEV_PROMETHEUS_PORT}
