global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert-rules.yml

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'dekk-was-server'
          environment: 'dev'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
