CREATE TABLE active_logs
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    user_id    BIGINT                                  NOT NULL,
    card_id    BIGINT                                  NOT NULL,
    swipe_type VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_active_logs PRIMARY KEY (id)
);

CREATE TABLE admins
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    email      VARCHAR(255),
    password   VARCHAR(255),
    admin_role VARCHAR(255),
    CONSTRAINT pk_admins PRIMARY KEY (id)
);

CREATE TABLE card_categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    card_id     BIGINT                                  NOT NULL,
    category_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_card_categories PRIMARY KEY (id)
);

CREATE TABLE card_delete_reasons
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    card_id    BIGINT                                  NOT NULL,
    admin_id   BIGINT                                  NOT NULL,
    reason     VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_card_delete_reasons PRIMARY KEY (id)
);

CREATE TABLE card_images
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    card_id     BIGINT,
    origin_url  TEXT                                    NOT NULL,
    image_url   TEXT,
    is_uploaded BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_card_images PRIMARY KEY (id)
);

CREATE TABLE card_products
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    card_id    BIGINT                                  NOT NULL,
    product_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_card_products PRIMARY KEY (id)
);

CREATE TABLE cards
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    tags          VARCHAR(255),
    origin_id     VARCHAR(255)                            NOT NULL,
    status        VARCHAR(255)                            NOT NULL,
    platform      VARCHAR(255)                            NOT NULL,
    target_gender VARCHAR(255),
    height        INTEGER,
    weight        INTEGER,
    CONSTRAINT pk_cards PRIMARY KEY (id)
);

CREATE TABLE categories
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    parent_id  BIGINT,
    name       VARCHAR(10)                             NOT NULL,
    depth      INTEGER                                 NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE crawl_batches
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    platform   VARCHAR(255)                            NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_crawl_batches PRIMARY KEY (id)
);

CREATE TABLE crawl_raw_datas
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    batch_id    BIGINT                                  NOT NULL,
    platform    VARCHAR(255)                            NOT NULL,
    raw_data    TEXT                                    NOT NULL,
    status      VARCHAR(255)                            NOT NULL,
    retry_count INTEGER                                 NOT NULL,
    CONSTRAINT pk_crawl_raw_datas PRIMARY KEY (id)
);

CREATE TABLE deck_cards
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deck_id    BIGINT                                  NOT NULL,
    card_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_deck_cards PRIMARY KEY (id)
);

CREATE TABLE deck_members
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deck_id    BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    role       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_deck_members PRIMARY KEY (id)
);

CREATE TABLE decks
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    user_id    BIGINT                                  NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    deck_type  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_decks PRIMARY KEY (id)
);

CREATE TABLE image_inspections
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    card_image_id BIGINT                                  NOT NULL,
    image_url     TEXT                                    NOT NULL,
    status        VARCHAR(50)                             NOT NULL,
    ai_comment    VARCHAR(500),
    admin_id      BIGINT,
    deleted       BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_image_inspections PRIMARY KEY (id)
);

CREATE TABLE product_images
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id  BIGINT,
    origin_url  TEXT                                    NOT NULL,
    image_url   TEXT,
    is_uploaded BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_product_images PRIMARY KEY (id)
);

CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    brand       VARCHAR(255)                            NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    price       INTEGER,
    origin_id   VARCHAR(255)                            NOT NULL,
    option      VARCHAR(255),
    is_similar  BOOLEAN                                 NOT NULL,
    product_url TEXT,
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE profiles
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT                                  NOT NULL,
    height   INTEGER                                 NOT NULL,
    weight   INTEGER                                 NOT NULL,
    nickname VARCHAR(10)                             NOT NULL,
    gender   VARCHAR(255),
    CONSTRAINT pk_profiles PRIMARY KEY (id)
);

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    email       VARCHAR(255)                            NOT NULL,
    role        VARCHAR(255)                            NOT NULL,
    provider    VARCHAR(255)                            NOT NULL,
    provider_id VARCHAR(255)                            NOT NULL,
    status      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE card_images
    ADD CONSTRAINT uc_card_images_card UNIQUE (card_id);

ALTER TABLE product_images
    ADD CONSTRAINT uc_product_images_product UNIQUE (product_id);

ALTER TABLE profiles
    ADD CONSTRAINT uc_profiles_nickname UNIQUE (nickname);

ALTER TABLE profiles
    ADD CONSTRAINT uc_profiles_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE active_logs
    ADD CONSTRAINT uk_active_logs_user_card UNIQUE (user_id, card_id);

ALTER TABLE admins
    ADD CONSTRAINT uk_admin_email UNIQUE (email);

CREATE INDEX idx_image_inspections_card_image ON image_inspections (card_image_id);

CREATE INDEX idx_image_inspections_status ON image_inspections (status);

CREATE INDEX idx_user_card ON active_logs (user_id, card_id);

ALTER TABLE card_images
    ADD CONSTRAINT FK_CARD_IMAGES_ON_CARD FOREIGN KEY (card_id) REFERENCES cards (id);

ALTER TABLE card_products
    ADD CONSTRAINT FK_CARD_PRODUCTS_ON_CARD FOREIGN KEY (card_id) REFERENCES cards (id);

ALTER TABLE card_products
    ADD CONSTRAINT FK_CARD_PRODUCTS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE categories
    ADD CONSTRAINT FK_CATEGORIES_ON_PARENT FOREIGN KEY (parent_id) REFERENCES categories (id);

ALTER TABLE crawl_raw_datas
    ADD CONSTRAINT FK_CRAWL_RAW_DATAS_ON_BATCH FOREIGN KEY (batch_id) REFERENCES crawl_batches (id);

ALTER TABLE product_images
    ADD CONSTRAINT FK_PRODUCT_IMAGES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE profiles
    ADD CONSTRAINT FK_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
