-- ============================================================
-- Tables
-- ============================================================

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    gender character varying(255),
    height double precision,
    nickname character varying(255),
    provider character varying(255) NOT NULL,
    provider_id character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    weight double precision,
    CONSTRAINT users_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT users_provider_check CHECK (((provider)::text = ANY ((ARRAY['GOOGLE'::character varying, 'KAKAO'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['MEMBER'::character varying, 'SELLER'::character varying, 'ADMIN'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACTIVE'::character varying, 'INACTIVE'::character varying, 'DELETED'::character varying])::text[])))
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.admins (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    admin_role character varying(255),
    email character varying(255),
    password character varying(255),
    CONSTRAINT admins_admin_role_check CHECK (((admin_role)::text = ANY ((ARRAY['SUPER_ADMIN'::character varying, 'ADMIN'::character varying])::text[])))
);

ALTER TABLE public.admins ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admins_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.profiles (
    id bigint NOT NULL,
    gender character varying(255),
    height integer NOT NULL,
    nickname character varying(10) NOT NULL,
    weight integer NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT profiles_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'OTHER'::character varying])::text[])))
);

ALTER TABLE public.profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.categories (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    depth integer NOT NULL,
    name character varying(10) NOT NULL,
    parent_id bigint
);

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.cards (
    id bigint NOT NULL,
    height integer,
    is_active boolean NOT NULL,
    origin_id character varying(255) NOT NULL,
    platform character varying(255) NOT NULL,
    tags character varying(255),
    weight integer,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    target_gender character varying(255),
    CONSTRAINT cards_platform_check CHECK (((platform)::text = ANY ((ARRAY['MUSINSA'::character varying, 'ZIGZAG'::character varying, 'ABLY'::character varying])::text[]))),
    CONSTRAINT cards_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'DELETE_REQUESTED'::character varying])::text[]))),
    CONSTRAINT cards_target_gender_check CHECK (((target_gender)::text = ANY ((ARRAY['WOMEN'::character varying, 'MEN'::character varying, 'OTHER'::character varying, 'UNDEFINED'::character varying])::text[])))
);

ALTER TABLE public.cards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.card_images (
    id bigint NOT NULL,
    image_url character varying(255),
    is_uploaded boolean NOT NULL,
    origin_url character varying(255) NOT NULL,
    card_id bigint
);

ALTER TABLE public.card_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.card_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.products (
    id bigint NOT NULL,
    gender character varying(255),
    is_similar boolean NOT NULL,
    name character varying(255) NOT NULL,
    option character varying(255),
    origin_id character varying(255) NOT NULL,
    price integer,
    product_url character varying(255),
    brand character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean NOT NULL,
    CONSTRAINT products_gender_check CHECK (((gender)::text = ANY ((ARRAY['WOMEN'::character varying, 'MEN'::character varying, 'UNISEX'::character varying, 'UNDEFINED'::character varying])::text[])))
);

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.product_images (
    id bigint NOT NULL,
    image_url character varying(255),
    is_uploaded boolean NOT NULL,
    origin_url character varying(255) NOT NULL,
    product_id bigint
);

ALTER TABLE public.product_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.card_products (
    id bigint NOT NULL,
    card_id bigint NOT NULL,
    product_id bigint NOT NULL
);

ALTER TABLE public.card_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.card_products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.card_categories (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    card_id bigint NOT NULL,
    category_id bigint NOT NULL
);

ALTER TABLE public.card_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.card_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.decks (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_default boolean NOT NULL,
    name character varying(255) NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.decks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.decks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.deck_cards (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    card_id bigint NOT NULL,
    deck_id bigint NOT NULL
);

ALTER TABLE public.deck_cards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deck_cards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.active_logs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    card_id bigint NOT NULL,
    swipe_type character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT active_logs_swipe_type_check CHECK (((swipe_type)::text = ANY ((ARRAY['LIKE'::character varying, 'DISLIKE'::character varying])::text[])))
);

ALTER TABLE public.active_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.active_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.crawl_batches (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    platform character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT crawl_batches_platform_check CHECK (((platform)::text = ANY ((ARRAY['MUSINSA'::character varying, 'ZIGZAG'::character varying, 'ABLY'::character varying])::text[]))),
    CONSTRAINT crawl_batches_status_check CHECK (((status)::text = ANY ((ARRAY['COLLECTING'::character varying, 'COLLECTED'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying])::text[])))
);

ALTER TABLE public.crawl_batches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crawl_batches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.crawl_raw_datas (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    platform character varying(255) NOT NULL,
    raw_data text NOT NULL,
    retry_count integer NOT NULL,
    status character varying(255) NOT NULL,
    batch_id bigint NOT NULL,
    CONSTRAINT crawl_raw_datas_platform_check CHECK (((platform)::text = ANY ((ARRAY['MUSINSA'::character varying, 'ZIGZAG'::character varying, 'ABLY'::character varying])::text[]))),
    CONSTRAINT crawl_raw_datas_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);

ALTER TABLE public.crawl_raw_datas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crawl_raw_datas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ============================================================
-- Primary Keys
-- ============================================================

ALTER TABLE ONLY public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.admins ADD CONSTRAINT admins_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.categories ADD CONSTRAINT categories_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.cards ADD CONSTRAINT cards_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.card_images ADD CONSTRAINT card_images_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.products ADD CONSTRAINT products_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.product_images ADD CONSTRAINT product_images_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.card_products ADD CONSTRAINT card_products_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.card_categories ADD CONSTRAINT card_categories_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.decks ADD CONSTRAINT decks_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.deck_cards ADD CONSTRAINT deck_cards_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.active_logs ADD CONSTRAINT active_logs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.crawl_batches ADD CONSTRAINT crawl_batches_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.crawl_raw_datas ADD CONSTRAINT crawl_raw_datas_pkey PRIMARY KEY (id);

-- ============================================================
-- Unique Constraints
-- ============================================================

ALTER TABLE ONLY public.users ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);
ALTER TABLE ONLY public.admins ADD CONSTRAINT uk_admin_email UNIQUE (email);
ALTER TABLE ONLY public.profiles ADD CONSTRAINT uk4ixsj6aqve5pxrbw2u0oyk8bb UNIQUE (user_id);
ALTER TABLE ONLY public.profiles ADD CONSTRAINT uko3sh06ntflsc73hf6x6obygca UNIQUE (nickname);
ALTER TABLE ONLY public.card_images ADD CONSTRAINT ukrl6p46r42wlf5h1a7qq5w14ro UNIQUE (card_id);
ALTER TABLE ONLY public.product_images ADD CONSTRAINT ukj6vpvxdkrgqdhqs0s1dlqhp6j UNIQUE (product_id);
ALTER TABLE ONLY public.active_logs ADD CONSTRAINT uk_active_logs_user_card UNIQUE (user_id, card_id);

-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX idx_user_card ON public.active_logs USING btree (user_id, card_id);

-- ============================================================
-- Foreign Keys
-- ============================================================

ALTER TABLE ONLY public.profiles ADD CONSTRAINT fk410q61iev7klncmpqfuo85ivh FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.categories ADD CONSTRAINT fksaok720gsu4u2wrgbk10b5n8d FOREIGN KEY (parent_id) REFERENCES public.categories(id);
ALTER TABLE ONLY public.card_images ADD CONSTRAINT fk5yh529h49s8o4kc7lnoi2xex0 FOREIGN KEY (card_id) REFERENCES public.cards(id);
ALTER TABLE ONLY public.product_images ADD CONSTRAINT fkqnq71xsohugpqwf3c9gxmsuy FOREIGN KEY (product_id) REFERENCES public.products(id);
ALTER TABLE ONLY public.card_products ADD CONSTRAINT fk4h2uth0nw5u58y27xvkpbq9qi FOREIGN KEY (card_id) REFERENCES public.cards(id);
ALTER TABLE ONLY public.card_products ADD CONSTRAINT fkmj307lib307lc6juj1jrao9mx FOREIGN KEY (product_id) REFERENCES public.products(id);
ALTER TABLE ONLY public.crawl_raw_datas ADD CONSTRAINT fkiyutiddm7l0fwy6sney1c85r6 FOREIGN KEY (batch_id) REFERENCES public.crawl_batches(id);
