-- ============================================================
-- V4: deck_members 테이블 신규 생성 및 데이터 마이그레이션
-- ============================================================

CREATE TABLE public.deck_members
(
    id         bigint                 NOT NULL,
    deck_id    bigint                 NOT NULL,
    user_id    bigint                 NOT NULL,
    role       character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    CONSTRAINT deck_members_role_check CHECK (((role):: text = ANY
                                               ((ARRAY ['HOST':: character varying, 'GUEST':: character varying]):: text[])))
);

ALTER TABLE public.deck_members
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.deck_members_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );

ALTER TABLE ONLY public.deck_members
    ADD CONSTRAINT deck_members_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.deck_members
    ADD CONSTRAINT fk_deck_members_deck_id FOREIGN KEY (deck_id) REFERENCES public.decks (id);

ALTER TABLE ONLY public.deck_members
    ADD CONSTRAINT fk_deck_members_user_id FOREIGN KEY (user_id) REFERENCES public.users (id);

CREATE INDEX idx_deck_members_user_id ON public.deck_members USING btree (user_id);

CREATE UNIQUE INDEX uk_deck_member_user_deck ON public.deck_members (user_id, deck_id) WHERE deleted_at IS NULL;

COMMENT ON TABLE public.deck_members IS '보관함-유저 권한 매핑 테이블 (쉐어덱)';
COMMENT ON COLUMN public.deck_members.role IS '권한 (HOST, GUEST)';

INSERT INTO public.deck_members (deck_id, user_id, role, created_at, updated_at)
SELECT id, user_id, 'HOST', created_at, CURRENT_TIMESTAMP
FROM public.decks;
