CREATE TABLE public.image_inspections
(
    id            bigint                                                     NOT NULL,
    card_image_id bigint                                                     NOT NULL,
    image_url     text                                                       NOT NULL,
    product_title character varying(255)                                     NOT NULL,
    status        character varying(50) DEFAULT 'PENDING'::character varying NOT NULL,
    ai_comment    character varying(500),
    deleted       boolean               DEFAULT false                        NOT NULL,
    created_at    timestamp(6) without time zone                             NOT NULL,
    updated_at    timestamp(6) without time zone                             NOT NULL,
    deleted_at    timestamp(6) without time zone
);

ALTER TABLE public.image_inspections
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS
        IDENTITY (
        SEQUENCE NAME public.image_inspections_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );

ALTER TABLE ONLY public.image_inspections
    ADD CONSTRAINT image_inspections_pkey
        PRIMARY KEY (id);

CREATE INDEX idx_image_inspections_card_image ON public.image_inspections USING
    btree (card_image_id);

CREATE INDEX idx_image_inspections_status ON public.image_inspections USING btree
    (status);

COMMENT ON TABLE public.image_inspections IS '이미지 AI 검수 결과 테이블';
COMMENT ON COLUMN public.image_inspections.status IS '검수 상태 (DEFAULT: PENDING)';
COMMENT ON COLUMN public.image_inspections.ai_comment IS 'AI 검수 결과 상세 코멘트';
