-- ============================================================
-- V6: card_delete_reasons 테이블 신규 생성
-- ============================================================

CREATE TABLE public.card_delete_reasons
(
    id         bigint                 NOT NULL,
    card_id    bigint                 NOT NULL,
    admin_id   bigint                 NOT NULL,
    reason     character varying(100) NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone
);

ALTER TABLE public.card_delete_reasons
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.card_delete_reasons_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );

ALTER TABLE ONLY public.card_delete_reasons
    ADD CONSTRAINT card_delete_reasons_pkey PRIMARY KEY (id);

COMMENT ON TABLE public.card_delete_reasons IS '카드 삭제 요청 사유 및 관리자 정보 기록 테이블';
COMMENT ON COLUMN public.card_delete_reasons.card_id IS '삭제 요청된 카드 ID (FK 없음)';
COMMENT ON COLUMN public.card_delete_reasons.admin_id IS '삭제를 요청한 관리자 ID (FK 없음)';
COMMENT ON COLUMN public.card_delete_reasons.reason IS '삭제 사유 (최대 100자)';
