CREATE TABLE public.resources
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
    public_id          UUID                                                  NOT NULL,
    resource_type      VARCHAR(20)                                           NOT NULL,
    status             VARCHAR(20)                 DEFAULT 'PENDING'         NOT NULL,
    image_url          VARCHAR(500),
    original_key       VARCHAR(500),
    original_file_name VARCHAR(255),
    processed_key      VARCHAR(500),
    content_type       VARCHAR(100),
    file_size          BIGINT,
    expires_at         TIMESTAMP WITHOUT TIME ZONE,
    created_at         TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_resources PRIMARY KEY (id),
    CONSTRAINT uk_resources_public_id UNIQUE (public_id)
);

CREATE INDEX idx_resources_status ON public.resources (status);
CREATE INDEX idx_resources_expires_at ON public.resources (expires_at);
